Rework CI to test that this builds. (#72)
* CI `build-from-source` instead of `build-bundled`

* remove pkg-config builds for now

* Get ubuntu building sdl3 from source.

* use a new vcpkg repo target that actually has sdl3

* fix actions being in wrong folder

whoops

* vcpkg libxcrypt linux dependency

* maybe

* maybe

* disable vcpkg builds for now as linking is failing

* disable windows builds until I can figure out why they're broken in CI
(error C1083: Cannot open include file: 'gameinput.h': No such file or directory)

* Don't bother running `cargo test` until tests are fixed.

* also build the `raw-window-handle` feature in CI

* build with both "raw-window-handle" and "build-from-source" features in CI

* cargo fmt